module ApplicationCable
  class Connection < ActionCable::Connection::Base
    # Authentication methods generated by authentication generator
    identified_by :current_user

    def connect
      self.current_user = find_verified_user
    end

    private

    def find_verified_user
      # Try to authenticate via session token from cookies
      if session_token = cookies.signed[:session_token]
        if session_record = Session.find_by(id: session_token)
          session_record.user
        else
          reject_unauthorized_connection
        end
      # Try to authenticate via Authorization header (for API clients)
      elsif auth_header = request.headers['Authorization']
        token = auth_header.gsub(/Bearer\s+/, '')
        if session_record = Session.find_by(id: token)
          session_record.user
        else
          reject_unauthorized_connection
        end
      else
        reject_unauthorized_connection
      end
    end
    # Authentication methods generated end

    # identified_by :session_id

    # We can access request/cookies object directly here
    # def connect
    #   self.session_id = request.session[:chat_session_id]
    # end
  end
end
