class Api::BaseController < ActionController::API
  # API Authentication methods generated by authentication generator
  before_action :set_current_request_details
  # API Authentication public methods generated end

  # ActionController::API doesn't include CSRF protection by default

  # Use unified error handling from FriendlyErrorHandlingConcern
  include FriendlyErrorHandlingConcern

  # API Authentication private methods begin
  private

  def current_user
    Current.session&.user
  end

  def user_signed_in?
    current_user.present?
  end

  def authenticate_user!
    if session_record = find_session_record
      Current.session = session_record
    else
      render json: { error: 'Unauthorized' }, status: :unauthorized
    end
  end

  alias_method :authenticate, :authenticate_user!
  alias_method :require_authentication, :authenticate_user!

  def set_current_request_details
    Current.user_agent = request.user_agent
    Current.ip_address = request.ip

    if session_record = find_session_record
      Current.session = session_record
    end
  end

  def find_session_record
    # API authentication via Authorization header only
    # ActionController::API does not support cookies
    if request.headers['Authorization'].present?
      token = request.headers['Authorization'].gsub(/Bearer\s+/, '')
      return Session.find_by_id(token)
    end

    nil
  end
  # API Authentication private methods end
end

