class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?

    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do
  # Routes for consultations generated by controller generator
  resources :consultations, only: [:index]
  # End routes for consultations

  # Routes for teams generated by controller generator
  resources :teams, only: [:index]
  # End routes for teams

  # Routes for wechat_signatures generated by controller generator
  resources :wechat_signatures, only: [:create]
  # End routes for wechat_signatures

  # Routes for onboardings generated by controller generator
  resources :onboardings, only: [:index] do
    collection do
      post :skip
    end
  end
  # End routes for onboardings

  # Routes for dashboards generated by controller generator
  resources :dashboards, only: [:index] do
    collection do
      get :case_studies
      get :honors
      get :settings
      patch :settings, action: :update_settings
      get :share_card
    end
  end
  
  # User's own case studies and honors management
  namespace :dashboards do
    resources :case_studies, path: 'my/case_studies'
    resources :honors, path: 'my/honors'
  end
  # End routes for dashboards

  # Public profile card routes
  resources :cards, only: [:show], path: 'c'
  # End routes for cards

  # Authentication routes generated by authentication generator
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete 'sign_out', to: 'sessions#destroy', as: :sign_out
  # Disabled: Only allow registration through invitation
  # get  "sign_up", to: "registrations#new"
  # post "sign_up", to: "registrations#create"
  resource :session, only: [:new, :show, :destroy] do
    get :devices, on: :member
    delete :destroy_one, on: :member
  end
  # Disabled: Only allow registration through invitation
  # resources :registrations, only: [:new, :create]
  resource  :password, only: [:edit, :update]

  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
    resource :registration_completion, only: [:edit, :update], path: 'complete-registration'
  end

  get  "/auth/failure",            to: "sessions/omniauth#failure"
  get  "/auth/:provider/callback", to: "sessions/omniauth#create"
  post "/auth/:provider/callback", to: "sessions/omniauth#create"

  resource :invitation, only: [:new, :create]

  # Profile routes
  resource :profile, only: [:show, :edit, :update], controller: 'profiles' do
    member do
      get :edit_password
      patch :update_password
    end
  end

  # Authentication routes generated end

  # write your business logic routes here

  # API routes
  namespace :api do
    namespace :v1 do
      # API authentication routes
      post 'login', to: 'sessions#login'
      delete 'logout', to: 'sessions#destroy'
      # Disabled: Only allow registration through invitation
      # post 'sign_up', to: 'registrations#create'
      resource :profile, only: [:show, :update], controller: 'profiles'
      put 'password', to: 'profiles#update_password'

      get 'health', to: 'health#index'
    end
  end

  root 'home#index'

  # Do not write business logic at admin dashboard
  namespace :admin do
    resource :organization, only: [:edit, :update] do
      get :members, on: :member
      post 'members/:profile_id/approve', action: :approve_member, as: :approve_member, on: :member
      post 'members/:profile_id/reject', action: :reject_member, as: :reject_member, on: :member
      post 'members/:profile_id/reactivate', action: :reactivate_member, as: :reactivate_member, on: :member
      delete 'members/:profile_id/destroy', action: :destroy_member, as: :destroy_member, on: :member
      post 'members/:profile_id/resend_email', action: :resend_approval_email, as: :resend_email_member, on: :member
      post :add_user, on: :member
    end
    resources :honors
    resources :case_studies
    resources :profiles do
      post :regenerate_specializations, on: :member
    end
    resources :admin_oplogs, only: [:index, :show]
    resources :administrators
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]

    # Mount GoodJob dashboard
    mount GoodJob::Engine => 'good_job', :constraints => AdminConstraint.new

    root to: 'dashboard#index'
  end

  mount ActionCable.server => '/cable'

  # Catch-all route for all 404 errors - MUST be last
  match '*path', to: 'application#handle_routing_error', via: :all,
    constraints: lambda { |request|
      !request.path.start_with?('/rails/active_storage')
    }
end
